/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProtectedRouteImport } from './routes/_protected'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ProtectedIndexRouteImport } from './routes/_protected/index'
import { Route as ProtectedAdminRouteImport } from './routes/_protected/admin'
import { Route as ProtectedReportsRouteImport } from './routes/_protected/reports'
import { Route as ApiCountriesRouteImport } from './routes/api/countries'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as ApiMeRouteImport } from './routes/api/me'
import { Route as ApiRequestsRouteImport } from './routes/api/requests'
import { Route as ApiScreenshotsRouteImport } from './routes/api/screenshots'
import { Route as ApiUsersRouteImport } from './routes/api/users'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiChannelsIdRouteImport } from './routes/api/channels/$id'
import { Route as ApiCountriesIdRouteImport } from './routes/api/countries/$id'
import { Route as ApiRegionsIdRouteImport } from './routes/api/regions/$id'
import { Route as ApiReportsByUserRouteImport } from './routes/api/reports/by-user'
import { Route as ApiRequestsIdRouteImport } from './routes/api/requests/$id'
import { Route as ApiScreenshotsKeyRouteImport } from './routes/api/screenshots/$key'
import { Route as ApiUsersInviteRouteImport } from './routes/api/users/invite'
import { Route as ApiChannelsIdTestRouteImport } from './routes/api/channels/$id/test'
import { Route as ApiCountriesIdChannelsRouteImport } from './routes/api/countries/$id/channels'
import { Route as ApiCountriesIdRegionsRouteImport } from './routes/api/countries/$id/regions'
import { Route as ApiUsersIdAccessRouteImport } from './routes/api/users/$id/access'
import { Route as ApiUsersIdResetPasswordRouteImport } from './routes/api/users/$id/reset-password'

const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedIndexRoute = ProtectedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedAdminRoute = ProtectedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedReportsRoute = ProtectedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => ProtectedRoute,
} as any)
const ApiCountriesRoute = ApiCountriesRouteImport.update({
  id: '/api/countries',
  path: '/api/countries',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMeRoute = ApiMeRouteImport.update({
  id: '/api/me',
  path: '/api/me',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRequestsRoute = ApiRequestsRouteImport.update({
  id: '/api/requests',
  path: '/api/requests',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiScreenshotsRoute = ApiScreenshotsRouteImport.update({
  id: '/api/screenshots',
  path: '/api/screenshots',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUsersRoute = ApiUsersRouteImport.update({
  id: '/api/users',
  path: '/api/users',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChannelsIdRoute = ApiChannelsIdRouteImport.update({
  id: '/api/channels/$id',
  path: '/api/channels/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCountriesIdRoute = ApiCountriesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiCountriesRoute,
} as any)
const ApiRegionsIdRoute = ApiRegionsIdRouteImport.update({
  id: '/api/regions/$id',
  path: '/api/regions/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiReportsByUserRoute = ApiReportsByUserRouteImport.update({
  id: '/api/reports/by-user',
  path: '/api/reports/by-user',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRequestsIdRoute = ApiRequestsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiRequestsRoute,
} as any)
const ApiScreenshotsKeyRoute = ApiScreenshotsKeyRouteImport.update({
  id: '/$key',
  path: '/$key',
  getParentRoute: () => ApiScreenshotsRoute,
} as any)
const ApiUsersInviteRoute = ApiUsersInviteRouteImport.update({
  id: '/invite',
  path: '/invite',
  getParentRoute: () => ApiUsersRoute,
} as any)
const ApiChannelsIdTestRoute = ApiChannelsIdTestRouteImport.update({
  id: '/test',
  path: '/test',
  getParentRoute: () => ApiChannelsIdRoute,
} as any)
const ApiCountriesIdChannelsRoute = ApiCountriesIdChannelsRouteImport.update({
  id: '/channels',
  path: '/channels',
  getParentRoute: () => ApiCountriesIdRoute,
} as any)
const ApiCountriesIdRegionsRoute = ApiCountriesIdRegionsRouteImport.update({
  id: '/regions',
  path: '/regions',
  getParentRoute: () => ApiCountriesIdRoute,
} as any)
const ApiUsersIdAccessRoute = ApiUsersIdAccessRouteImport.update({
  id: '/$id/access',
  path: '/$id/access',
  getParentRoute: () => ApiUsersRoute,
} as any)
const ApiUsersIdResetPasswordRoute = ApiUsersIdResetPasswordRouteImport.update({
  id: '/$id/reset-password',
  path: '/$id/reset-password',
  getParentRoute: () => ApiUsersRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof ProtectedIndexRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin': typeof ProtectedAdminRoute
  '/reports': typeof ProtectedReportsRoute
  '/api/countries': typeof ApiCountriesRouteWithChildren
  '/api/health': typeof ApiHealthRoute
  '/api/me': typeof ApiMeRoute
  '/api/requests': typeof ApiRequestsRouteWithChildren
  '/api/screenshots': typeof ApiScreenshotsRouteWithChildren
  '/api/users': typeof ApiUsersRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/channels/$id': typeof ApiChannelsIdRouteWithChildren
  '/api/countries/$id': typeof ApiCountriesIdRouteWithChildren
  '/api/regions/$id': typeof ApiRegionsIdRoute
  '/api/reports/by-user': typeof ApiReportsByUserRoute
  '/api/requests/$id': typeof ApiRequestsIdRoute
  '/api/screenshots/$key': typeof ApiScreenshotsKeyRoute
  '/api/users/invite': typeof ApiUsersInviteRoute
  '/api/channels/$id/test': typeof ApiChannelsIdTestRoute
  '/api/countries/$id/channels': typeof ApiCountriesIdChannelsRoute
  '/api/countries/$id/regions': typeof ApiCountriesIdRegionsRoute
  '/api/users/$id/access': typeof ApiUsersIdAccessRoute
  '/api/users/$id/reset-password': typeof ApiUsersIdResetPasswordRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin': typeof ProtectedAdminRoute
  '/reports': typeof ProtectedReportsRoute
  '/api/countries': typeof ApiCountriesRouteWithChildren
  '/api/health': typeof ApiHealthRoute
  '/api/me': typeof ApiMeRoute
  '/api/requests': typeof ApiRequestsRouteWithChildren
  '/api/screenshots': typeof ApiScreenshotsRouteWithChildren
  '/api/users': typeof ApiUsersRouteWithChildren
  '/': typeof ProtectedIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/channels/$id': typeof ApiChannelsIdRouteWithChildren
  '/api/countries/$id': typeof ApiCountriesIdRouteWithChildren
  '/api/regions/$id': typeof ApiRegionsIdRoute
  '/api/reports/by-user': typeof ApiReportsByUserRoute
  '/api/requests/$id': typeof ApiRequestsIdRoute
  '/api/screenshots/$key': typeof ApiScreenshotsKeyRoute
  '/api/users/invite': typeof ApiUsersInviteRoute
  '/api/channels/$id/test': typeof ApiChannelsIdTestRoute
  '/api/countries/$id/channels': typeof ApiCountriesIdChannelsRoute
  '/api/countries/$id/regions': typeof ApiCountriesIdRegionsRoute
  '/api/users/$id/access': typeof ApiUsersIdAccessRoute
  '/api/users/$id/reset-password': typeof ApiUsersIdResetPasswordRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_protected': typeof ProtectedRouteWithChildren
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_protected/admin': typeof ProtectedAdminRoute
  '/_protected/reports': typeof ProtectedReportsRoute
  '/api/countries': typeof ApiCountriesRouteWithChildren
  '/api/health': typeof ApiHealthRoute
  '/api/me': typeof ApiMeRoute
  '/api/requests': typeof ApiRequestsRouteWithChildren
  '/api/screenshots': typeof ApiScreenshotsRouteWithChildren
  '/api/users': typeof ApiUsersRouteWithChildren
  '/_protected/': typeof ProtectedIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/channels/$id': typeof ApiChannelsIdRouteWithChildren
  '/api/countries/$id': typeof ApiCountriesIdRouteWithChildren
  '/api/regions/$id': typeof ApiRegionsIdRoute
  '/api/reports/by-user': typeof ApiReportsByUserRoute
  '/api/requests/$id': typeof ApiRequestsIdRoute
  '/api/screenshots/$key': typeof ApiScreenshotsKeyRoute
  '/api/users/invite': typeof ApiUsersInviteRoute
  '/api/channels/$id/test': typeof ApiChannelsIdTestRoute
  '/api/countries/$id/channels': typeof ApiCountriesIdChannelsRoute
  '/api/countries/$id/regions': typeof ApiCountriesIdRegionsRoute
  '/api/users/$id/access': typeof ApiUsersIdAccessRoute
  '/api/users/$id/reset-password': typeof ApiUsersIdResetPasswordRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/reset-password'
    | '/admin'
    | '/reports'
    | '/api/countries'
    | '/api/health'
    | '/api/me'
    | '/api/requests'
    | '/api/screenshots'
    | '/api/users'
    | '/api/auth/$'
    | '/api/channels/$id'
    | '/api/countries/$id'
    | '/api/regions/$id'
    | '/api/reports/by-user'
    | '/api/requests/$id'
    | '/api/screenshots/$key'
    | '/api/users/invite'
    | '/api/channels/$id/test'
    | '/api/countries/$id/channels'
    | '/api/countries/$id/regions'
    | '/api/users/$id/access'
    | '/api/users/$id/reset-password'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/reset-password'
    | '/admin'
    | '/reports'
    | '/api/countries'
    | '/api/health'
    | '/api/me'
    | '/api/requests'
    | '/api/screenshots'
    | '/api/users'
    | '/'
    | '/api/auth/$'
    | '/api/channels/$id'
    | '/api/countries/$id'
    | '/api/regions/$id'
    | '/api/reports/by-user'
    | '/api/requests/$id'
    | '/api/screenshots/$key'
    | '/api/users/invite'
    | '/api/channels/$id/test'
    | '/api/countries/$id/channels'
    | '/api/countries/$id/regions'
    | '/api/users/$id/access'
    | '/api/users/$id/reset-password'
  id:
    | '__root__'
    | '/_protected'
    | '/login'
    | '/reset-password'
    | '/_protected/admin'
    | '/_protected/reports'
    | '/api/countries'
    | '/api/health'
    | '/api/me'
    | '/api/requests'
    | '/api/screenshots'
    | '/api/users'
    | '/_protected/'
    | '/api/auth/$'
    | '/api/channels/$id'
    | '/api/countries/$id'
    | '/api/regions/$id'
    | '/api/reports/by-user'
    | '/api/requests/$id'
    | '/api/screenshots/$key'
    | '/api/users/invite'
    | '/api/channels/$id/test'
    | '/api/countries/$id/channels'
    | '/api/countries/$id/regions'
    | '/api/users/$id/access'
    | '/api/users/$id/reset-password'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ProtectedRoute: typeof ProtectedRouteWithChildren
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ApiCountriesRoute: typeof ApiCountriesRouteWithChildren
  ApiHealthRoute: typeof ApiHealthRoute
  ApiMeRoute: typeof ApiMeRoute
  ApiRequestsRoute: typeof ApiRequestsRouteWithChildren
  ApiScreenshotsRoute: typeof ApiScreenshotsRouteWithChildren
  ApiUsersRoute: typeof ApiUsersRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiChannelsIdRoute: typeof ApiChannelsIdRouteWithChildren
  ApiRegionsIdRoute: typeof ApiRegionsIdRoute
  ApiReportsByUserRoute: typeof ApiReportsByUserRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/': {
      id: '/_protected/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ProtectedIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/admin': {
      id: '/_protected/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof ProtectedAdminRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/reports': {
      id: '/_protected/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ProtectedReportsRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/api/countries': {
      id: '/api/countries'
      path: '/api/countries'
      fullPath: '/api/countries'
      preLoaderRoute: typeof ApiCountriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/me': {
      id: '/api/me'
      path: '/api/me'
      fullPath: '/api/me'
      preLoaderRoute: typeof ApiMeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/requests': {
      id: '/api/requests'
      path: '/api/requests'
      fullPath: '/api/requests'
      preLoaderRoute: typeof ApiRequestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/screenshots': {
      id: '/api/screenshots'
      path: '/api/screenshots'
      fullPath: '/api/screenshots'
      preLoaderRoute: typeof ApiScreenshotsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/users': {
      id: '/api/users'
      path: '/api/users'
      fullPath: '/api/users'
      preLoaderRoute: typeof ApiUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/channels/$id': {
      id: '/api/channels/$id'
      path: '/api/channels/$id'
      fullPath: '/api/channels/$id'
      preLoaderRoute: typeof ApiChannelsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/countries/$id': {
      id: '/api/countries/$id'
      path: '/$id'
      fullPath: '/api/countries/$id'
      preLoaderRoute: typeof ApiCountriesIdRouteImport
      parentRoute: typeof ApiCountriesRoute
    }
    '/api/regions/$id': {
      id: '/api/regions/$id'
      path: '/api/regions/$id'
      fullPath: '/api/regions/$id'
      preLoaderRoute: typeof ApiRegionsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/reports/by-user': {
      id: '/api/reports/by-user'
      path: '/api/reports/by-user'
      fullPath: '/api/reports/by-user'
      preLoaderRoute: typeof ApiReportsByUserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/requests/$id': {
      id: '/api/requests/$id'
      path: '/$id'
      fullPath: '/api/requests/$id'
      preLoaderRoute: typeof ApiRequestsIdRouteImport
      parentRoute: typeof ApiRequestsRoute
    }
    '/api/screenshots/$key': {
      id: '/api/screenshots/$key'
      path: '/$key'
      fullPath: '/api/screenshots/$key'
      preLoaderRoute: typeof ApiScreenshotsKeyRouteImport
      parentRoute: typeof ApiScreenshotsRoute
    }
    '/api/users/invite': {
      id: '/api/users/invite'
      path: '/invite'
      fullPath: '/api/users/invite'
      preLoaderRoute: typeof ApiUsersInviteRouteImport
      parentRoute: typeof ApiUsersRoute
    }
    '/api/channels/$id/test': {
      id: '/api/channels/$id/test'
      path: '/test'
      fullPath: '/api/channels/$id/test'
      preLoaderRoute: typeof ApiChannelsIdTestRouteImport
      parentRoute: typeof ApiChannelsIdRoute
    }
    '/api/countries/$id/channels': {
      id: '/api/countries/$id/channels'
      path: '/channels'
      fullPath: '/api/countries/$id/channels'
      preLoaderRoute: typeof ApiCountriesIdChannelsRouteImport
      parentRoute: typeof ApiCountriesIdRoute
    }
    '/api/countries/$id/regions': {
      id: '/api/countries/$id/regions'
      path: '/regions'
      fullPath: '/api/countries/$id/regions'
      preLoaderRoute: typeof ApiCountriesIdRegionsRouteImport
      parentRoute: typeof ApiCountriesIdRoute
    }
    '/api/users/$id/access': {
      id: '/api/users/$id/access'
      path: '/$id/access'
      fullPath: '/api/users/$id/access'
      preLoaderRoute: typeof ApiUsersIdAccessRouteImport
      parentRoute: typeof ApiUsersRoute
    }
    '/api/users/$id/reset-password': {
      id: '/api/users/$id/reset-password'
      path: '/$id/reset-password'
      fullPath: '/api/users/$id/reset-password'
      preLoaderRoute: typeof ApiUsersIdResetPasswordRouteImport
      parentRoute: typeof ApiUsersRoute
    }
  }
}

interface ProtectedRouteChildren {
  ProtectedAdminRoute: typeof ProtectedAdminRoute
  ProtectedReportsRoute: typeof ProtectedReportsRoute
  ProtectedIndexRoute: typeof ProtectedIndexRoute
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedAdminRoute: ProtectedAdminRoute,
  ProtectedReportsRoute: ProtectedReportsRoute,
  ProtectedIndexRoute: ProtectedIndexRoute,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

interface ApiCountriesIdRouteChildren {
  ApiCountriesIdChannelsRoute: typeof ApiCountriesIdChannelsRoute
  ApiCountriesIdRegionsRoute: typeof ApiCountriesIdRegionsRoute
}

const ApiCountriesIdRouteChildren: ApiCountriesIdRouteChildren = {
  ApiCountriesIdChannelsRoute: ApiCountriesIdChannelsRoute,
  ApiCountriesIdRegionsRoute: ApiCountriesIdRegionsRoute,
}

const ApiCountriesIdRouteWithChildren = ApiCountriesIdRoute._addFileChildren(
  ApiCountriesIdRouteChildren,
)

interface ApiCountriesRouteChildren {
  ApiCountriesIdRoute: typeof ApiCountriesIdRouteWithChildren
}

const ApiCountriesRouteChildren: ApiCountriesRouteChildren = {
  ApiCountriesIdRoute: ApiCountriesIdRouteWithChildren,
}

const ApiCountriesRouteWithChildren = ApiCountriesRoute._addFileChildren(
  ApiCountriesRouteChildren,
)

interface ApiRequestsRouteChildren {
  ApiRequestsIdRoute: typeof ApiRequestsIdRoute
}

const ApiRequestsRouteChildren: ApiRequestsRouteChildren = {
  ApiRequestsIdRoute: ApiRequestsIdRoute,
}

const ApiRequestsRouteWithChildren = ApiRequestsRoute._addFileChildren(
  ApiRequestsRouteChildren,
)

interface ApiScreenshotsRouteChildren {
  ApiScreenshotsKeyRoute: typeof ApiScreenshotsKeyRoute
}

const ApiScreenshotsRouteChildren: ApiScreenshotsRouteChildren = {
  ApiScreenshotsKeyRoute: ApiScreenshotsKeyRoute,
}

const ApiScreenshotsRouteWithChildren = ApiScreenshotsRoute._addFileChildren(
  ApiScreenshotsRouteChildren,
)

interface ApiUsersRouteChildren {
  ApiUsersInviteRoute: typeof ApiUsersInviteRoute
  ApiUsersIdAccessRoute: typeof ApiUsersIdAccessRoute
  ApiUsersIdResetPasswordRoute: typeof ApiUsersIdResetPasswordRoute
}

const ApiUsersRouteChildren: ApiUsersRouteChildren = {
  ApiUsersInviteRoute: ApiUsersInviteRoute,
  ApiUsersIdAccessRoute: ApiUsersIdAccessRoute,
  ApiUsersIdResetPasswordRoute: ApiUsersIdResetPasswordRoute,
}

const ApiUsersRouteWithChildren = ApiUsersRoute._addFileChildren(
  ApiUsersRouteChildren,
)

interface ApiChannelsIdRouteChildren {
  ApiChannelsIdTestRoute: typeof ApiChannelsIdTestRoute
}

const ApiChannelsIdRouteChildren: ApiChannelsIdRouteChildren = {
  ApiChannelsIdTestRoute: ApiChannelsIdTestRoute,
}

const ApiChannelsIdRouteWithChildren = ApiChannelsIdRoute._addFileChildren(
  ApiChannelsIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  ProtectedRoute: ProtectedRouteWithChildren,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ApiCountriesRoute: ApiCountriesRouteWithChildren,
  ApiHealthRoute: ApiHealthRoute,
  ApiMeRoute: ApiMeRoute,
  ApiRequestsRoute: ApiRequestsRouteWithChildren,
  ApiScreenshotsRoute: ApiScreenshotsRouteWithChildren,
  ApiUsersRoute: ApiUsersRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiChannelsIdRoute: ApiChannelsIdRouteWithChildren,
  ApiRegionsIdRoute: ApiRegionsIdRoute,
  ApiReportsByUserRoute: ApiReportsByUserRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
