/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProtectedRouteImport } from './routes/_protected'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as HelpRouteImport } from './routes/help'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as RequestsRouteImport } from './routes/requests'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as ProtectedAdminRouteImport } from './routes/_protected/admin'
import { Route as ProtectedReportsRouteImport } from './routes/_protected/reports'
import { Route as ApiCountriesRouteImport } from './routes/api/countries'
import { Route as ApiCredentialsRouteImport } from './routes/api/credentials'
import { Route as ApiFeedRouteImport } from './routes/api/feed'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as ApiMeRouteImport } from './routes/api/me'
import { Route as ApiRequestsRouteImport } from './routes/api/requests'
import { Route as ApiScreenshotsRouteImport } from './routes/api/screenshots'
import { Route as ApiUsersRouteImport } from './routes/api/users'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiChannelsIdRouteImport } from './routes/api/channels/$id'
import { Route as ApiCountriesIdRouteImport } from './routes/api/countries/$id'
import { Route as ApiCredentialsIdRouteImport } from './routes/api/credentials/$id'
import { Route as ApiPushSubscribeRouteImport } from './routes/api/push/subscribe'
import { Route as ApiPushSubscriptionsRouteImport } from './routes/api/push/subscriptions'
import { Route as ApiPushVapidPublicKeyRouteImport } from './routes/api/push/vapid-public-key'
import { Route as ApiRegionsIdRouteImport } from './routes/api/regions/$id'
import { Route as ApiReportsByUserRouteImport } from './routes/api/reports/by-user'
import { Route as ApiRequestsIdRouteImport } from './routes/api/requests/$id'
import { Route as ApiScreenshotsKeyRouteImport } from './routes/api/screenshots/$key'
import { Route as ApiUsersInviteRouteImport } from './routes/api/users/invite'
import { Route as ApiChannelsIdTestRouteImport } from './routes/api/channels/$id/test'
import { Route as ApiCountriesIdChannelsRouteImport } from './routes/api/countries/$id/channels'
import { Route as ApiCountriesIdRegionsRouteImport } from './routes/api/countries/$id/regions'
import { Route as ApiPushSubscriptionsIdRouteImport } from './routes/api/push/subscriptions/$id'
import { Route as ApiUsersIdAccessRouteImport } from './routes/api/users/$id/access'
import { Route as ApiUsersIdResetPasswordRouteImport } from './routes/api/users/$id/reset-password'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestsRoute = RequestsRouteImport.update({
  id: '/requests',
  path: '/requests',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedAdminRoute = ProtectedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedReportsRoute = ProtectedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => ProtectedRoute,
} as any)
const ApiCountriesRoute = ApiCountriesRouteImport.update({
  id: '/api/countries',
  path: '/api/countries',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCredentialsRoute = ApiCredentialsRouteImport.update({
  id: '/api/credentials',
  path: '/api/credentials',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFeedRoute = ApiFeedRouteImport.update({
  id: '/api/feed',
  path: '/api/feed',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMeRoute = ApiMeRouteImport.update({
  id: '/api/me',
  path: '/api/me',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRequestsRoute = ApiRequestsRouteImport.update({
  id: '/api/requests',
  path: '/api/requests',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiScreenshotsRoute = ApiScreenshotsRouteImport.update({
  id: '/api/screenshots',
  path: '/api/screenshots',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUsersRoute = ApiUsersRouteImport.update({
  id: '/api/users',
  path: '/api/users',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChannelsIdRoute = ApiChannelsIdRouteImport.update({
  id: '/api/channels/$id',
  path: '/api/channels/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCountriesIdRoute = ApiCountriesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiCountriesRoute,
} as any)
const ApiCredentialsIdRoute = ApiCredentialsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiCredentialsRoute,
} as any)
const ApiPushSubscribeRoute = ApiPushSubscribeRouteImport.update({
  id: '/api/push/subscribe',
  path: '/api/push/subscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPushSubscriptionsRoute = ApiPushSubscriptionsRouteImport.update({
  id: '/api/push/subscriptions',
  path: '/api/push/subscriptions',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPushVapidPublicKeyRoute = ApiPushVapidPublicKeyRouteImport.update({
  id: '/api/push/vapid-public-key',
  path: '/api/push/vapid-public-key',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRegionsIdRoute = ApiRegionsIdRouteImport.update({
  id: '/api/regions/$id',
  path: '/api/regions/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiReportsByUserRoute = ApiReportsByUserRouteImport.update({
  id: '/api/reports/by-user',
  path: '/api/reports/by-user',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRequestsIdRoute = ApiRequestsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiRequestsRoute,
} as any)
const ApiScreenshotsKeyRoute = ApiScreenshotsKeyRouteImport.update({
  id: '/$key',
  path: '/$key',
  getParentRoute: () => ApiScreenshotsRoute,
} as any)
const ApiUsersInviteRoute = ApiUsersInviteRouteImport.update({
  id: '/invite',
  path: '/invite',
  getParentRoute: () => ApiUsersRoute,
} as any)
const ApiChannelsIdTestRoute = ApiChannelsIdTestRouteImport.update({
  id: '/test',
  path: '/test',
  getParentRoute: () => ApiChannelsIdRoute,
} as any)
const ApiCountriesIdChannelsRoute = ApiCountriesIdChannelsRouteImport.update({
  id: '/channels',
  path: '/channels',
  getParentRoute: () => ApiCountriesIdRoute,
} as any)
const ApiCountriesIdRegionsRoute = ApiCountriesIdRegionsRouteImport.update({
  id: '/regions',
  path: '/regions',
  getParentRoute: () => ApiCountriesIdRoute,
} as any)
const ApiPushSubscriptionsIdRoute = ApiPushSubscriptionsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiPushSubscriptionsRoute,
} as any)
const ApiUsersIdAccessRoute = ApiUsersIdAccessRouteImport.update({
  id: '/$id/access',
  path: '/$id/access',
  getParentRoute: () => ApiUsersRoute,
} as any)
const ApiUsersIdResetPasswordRoute = ApiUsersIdResetPasswordRouteImport.update({
  id: '/$id/reset-password',
  path: '/$id/reset-password',
  getParentRoute: () => ApiUsersRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/help': typeof HelpRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/requests': typeof RequestsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/admin': typeof ProtectedAdminRoute
  '/reports': typeof ProtectedReportsRoute
  '/api/countries': typeof ApiCountriesRouteWithChildren
  '/api/credentials': typeof ApiCredentialsRouteWithChildren
  '/api/feed': typeof ApiFeedRoute
  '/api/health': typeof ApiHealthRoute
  '/api/me': typeof ApiMeRoute
  '/api/requests': typeof ApiRequestsRouteWithChildren
  '/api/screenshots': typeof ApiScreenshotsRouteWithChildren
  '/api/users': typeof ApiUsersRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/channels/$id': typeof ApiChannelsIdRouteWithChildren
  '/api/countries/$id': typeof ApiCountriesIdRouteWithChildren
  '/api/credentials/$id': typeof ApiCredentialsIdRoute
  '/api/push/subscribe': typeof ApiPushSubscribeRoute
  '/api/push/subscriptions': typeof ApiPushSubscriptionsRouteWithChildren
  '/api/push/vapid-public-key': typeof ApiPushVapidPublicKeyRoute
  '/api/regions/$id': typeof ApiRegionsIdRoute
  '/api/reports/by-user': typeof ApiReportsByUserRoute
  '/api/requests/$id': typeof ApiRequestsIdRoute
  '/api/screenshots/$key': typeof ApiScreenshotsKeyRoute
  '/api/users/invite': typeof ApiUsersInviteRoute
  '/api/channels/$id/test': typeof ApiChannelsIdTestRoute
  '/api/countries/$id/channels': typeof ApiCountriesIdChannelsRoute
  '/api/countries/$id/regions': typeof ApiCountriesIdRegionsRoute
  '/api/push/subscriptions/$id': typeof ApiPushSubscriptionsIdRoute
  '/api/users/$id/access': typeof ApiUsersIdAccessRoute
  '/api/users/$id/reset-password': typeof ApiUsersIdResetPasswordRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/help': typeof HelpRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/requests': typeof RequestsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/admin': typeof ProtectedAdminRoute
  '/reports': typeof ProtectedReportsRoute
  '/api/countries': typeof ApiCountriesRouteWithChildren
  '/api/credentials': typeof ApiCredentialsRouteWithChildren
  '/api/feed': typeof ApiFeedRoute
  '/api/health': typeof ApiHealthRoute
  '/api/me': typeof ApiMeRoute
  '/api/requests': typeof ApiRequestsRouteWithChildren
  '/api/screenshots': typeof ApiScreenshotsRouteWithChildren
  '/api/users': typeof ApiUsersRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/channels/$id': typeof ApiChannelsIdRouteWithChildren
  '/api/countries/$id': typeof ApiCountriesIdRouteWithChildren
  '/api/credentials/$id': typeof ApiCredentialsIdRoute
  '/api/push/subscribe': typeof ApiPushSubscribeRoute
  '/api/push/subscriptions': typeof ApiPushSubscriptionsRouteWithChildren
  '/api/push/vapid-public-key': typeof ApiPushVapidPublicKeyRoute
  '/api/regions/$id': typeof ApiRegionsIdRoute
  '/api/reports/by-user': typeof ApiReportsByUserRoute
  '/api/requests/$id': typeof ApiRequestsIdRoute
  '/api/screenshots/$key': typeof ApiScreenshotsKeyRoute
  '/api/users/invite': typeof ApiUsersInviteRoute
  '/api/channels/$id/test': typeof ApiChannelsIdTestRoute
  '/api/countries/$id/channels': typeof ApiCountriesIdChannelsRoute
  '/api/countries/$id/regions': typeof ApiCountriesIdRegionsRoute
  '/api/push/subscriptions/$id': typeof ApiPushSubscriptionsIdRoute
  '/api/users/$id/access': typeof ApiUsersIdAccessRoute
  '/api/users/$id/reset-password': typeof ApiUsersIdResetPasswordRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_protected': typeof ProtectedRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/help': typeof HelpRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/requests': typeof RequestsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/_protected/admin': typeof ProtectedAdminRoute
  '/_protected/reports': typeof ProtectedReportsRoute
  '/api/countries': typeof ApiCountriesRouteWithChildren
  '/api/credentials': typeof ApiCredentialsRouteWithChildren
  '/api/feed': typeof ApiFeedRoute
  '/api/health': typeof ApiHealthRoute
  '/api/me': typeof ApiMeRoute
  '/api/requests': typeof ApiRequestsRouteWithChildren
  '/api/screenshots': typeof ApiScreenshotsRouteWithChildren
  '/api/users': typeof ApiUsersRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/channels/$id': typeof ApiChannelsIdRouteWithChildren
  '/api/countries/$id': typeof ApiCountriesIdRouteWithChildren
  '/api/credentials/$id': typeof ApiCredentialsIdRoute
  '/api/push/subscribe': typeof ApiPushSubscribeRoute
  '/api/push/subscriptions': typeof ApiPushSubscriptionsRouteWithChildren
  '/api/push/vapid-public-key': typeof ApiPushVapidPublicKeyRoute
  '/api/regions/$id': typeof ApiRegionsIdRoute
  '/api/reports/by-user': typeof ApiReportsByUserRoute
  '/api/requests/$id': typeof ApiRequestsIdRoute
  '/api/screenshots/$key': typeof ApiScreenshotsKeyRoute
  '/api/users/invite': typeof ApiUsersInviteRoute
  '/api/channels/$id/test': typeof ApiChannelsIdTestRoute
  '/api/countries/$id/channels': typeof ApiCountriesIdChannelsRoute
  '/api/countries/$id/regions': typeof ApiCountriesIdRegionsRoute
  '/api/push/subscriptions/$id': typeof ApiPushSubscriptionsIdRoute
  '/api/users/$id/access': typeof ApiUsersIdAccessRoute
  '/api/users/$id/reset-password': typeof ApiUsersIdResetPasswordRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/help'
    | '/login'
    | '/privacy'
    | '/requests'
    | '/reset-password'
    | '/terms'
    | '/admin'
    | '/reports'
    | '/api/countries'
    | '/api/credentials'
    | '/api/feed'
    | '/api/health'
    | '/api/me'
    | '/api/requests'
    | '/api/screenshots'
    | '/api/users'
    | '/api/auth/$'
    | '/api/channels/$id'
    | '/api/countries/$id'
    | '/api/credentials/$id'
    | '/api/push/subscribe'
    | '/api/push/subscriptions'
    | '/api/push/vapid-public-key'
    | '/api/regions/$id'
    | '/api/reports/by-user'
    | '/api/requests/$id'
    | '/api/screenshots/$key'
    | '/api/users/invite'
    | '/api/channels/$id/test'
    | '/api/countries/$id/channels'
    | '/api/countries/$id/regions'
    | '/api/push/subscriptions/$id'
    | '/api/users/$id/access'
    | '/api/users/$id/reset-password'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/help'
    | '/login'
    | '/privacy'
    | '/requests'
    | '/reset-password'
    | '/terms'
    | '/admin'
    | '/reports'
    | '/api/countries'
    | '/api/credentials'
    | '/api/feed'
    | '/api/health'
    | '/api/me'
    | '/api/requests'
    | '/api/screenshots'
    | '/api/users'
    | '/api/auth/$'
    | '/api/channels/$id'
    | '/api/countries/$id'
    | '/api/credentials/$id'
    | '/api/push/subscribe'
    | '/api/push/subscriptions'
    | '/api/push/vapid-public-key'
    | '/api/regions/$id'
    | '/api/reports/by-user'
    | '/api/requests/$id'
    | '/api/screenshots/$key'
    | '/api/users/invite'
    | '/api/channels/$id/test'
    | '/api/countries/$id/channels'
    | '/api/countries/$id/regions'
    | '/api/push/subscriptions/$id'
    | '/api/users/$id/access'
    | '/api/users/$id/reset-password'
  id:
    | '__root__'
    | '/'
    | '/_protected'
    | '/forgot-password'
    | '/help'
    | '/login'
    | '/privacy'
    | '/requests'
    | '/reset-password'
    | '/terms'
    | '/_protected/admin'
    | '/_protected/reports'
    | '/api/countries'
    | '/api/credentials'
    | '/api/feed'
    | '/api/health'
    | '/api/me'
    | '/api/requests'
    | '/api/screenshots'
    | '/api/users'
    | '/api/auth/$'
    | '/api/channels/$id'
    | '/api/countries/$id'
    | '/api/credentials/$id'
    | '/api/push/subscribe'
    | '/api/push/subscriptions'
    | '/api/push/vapid-public-key'
    | '/api/regions/$id'
    | '/api/reports/by-user'
    | '/api/requests/$id'
    | '/api/screenshots/$key'
    | '/api/users/invite'
    | '/api/channels/$id/test'
    | '/api/countries/$id/channels'
    | '/api/countries/$id/regions'
    | '/api/push/subscriptions/$id'
    | '/api/users/$id/access'
    | '/api/users/$id/reset-password'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProtectedRoute: typeof ProtectedRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  HelpRoute: typeof HelpRoute
  LoginRoute: typeof LoginRoute
  PrivacyRoute: typeof PrivacyRoute
  RequestsRoute: typeof RequestsRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  TermsRoute: typeof TermsRoute
  ApiCountriesRoute: typeof ApiCountriesRouteWithChildren
  ApiCredentialsRoute: typeof ApiCredentialsRouteWithChildren
  ApiFeedRoute: typeof ApiFeedRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiMeRoute: typeof ApiMeRoute
  ApiRequestsRoute: typeof ApiRequestsRouteWithChildren
  ApiScreenshotsRoute: typeof ApiScreenshotsRouteWithChildren
  ApiUsersRoute: typeof ApiUsersRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiChannelsIdRoute: typeof ApiChannelsIdRouteWithChildren
  ApiPushSubscribeRoute: typeof ApiPushSubscribeRoute
  ApiPushSubscriptionsRoute: typeof ApiPushSubscriptionsRouteWithChildren
  ApiPushVapidPublicKeyRoute: typeof ApiPushVapidPublicKeyRoute
  ApiRegionsIdRoute: typeof ApiRegionsIdRoute
  ApiReportsByUserRoute: typeof ApiReportsByUserRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/requests': {
      id: '/requests'
      path: '/requests'
      fullPath: '/requests'
      preLoaderRoute: typeof RequestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/admin': {
      id: '/_protected/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof ProtectedAdminRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/reports': {
      id: '/_protected/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ProtectedReportsRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/api/countries': {
      id: '/api/countries'
      path: '/api/countries'
      fullPath: '/api/countries'
      preLoaderRoute: typeof ApiCountriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/credentials': {
      id: '/api/credentials'
      path: '/api/credentials'
      fullPath: '/api/credentials'
      preLoaderRoute: typeof ApiCredentialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/feed': {
      id: '/api/feed'
      path: '/api/feed'
      fullPath: '/api/feed'
      preLoaderRoute: typeof ApiFeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/me': {
      id: '/api/me'
      path: '/api/me'
      fullPath: '/api/me'
      preLoaderRoute: typeof ApiMeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/requests': {
      id: '/api/requests'
      path: '/api/requests'
      fullPath: '/api/requests'
      preLoaderRoute: typeof ApiRequestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/screenshots': {
      id: '/api/screenshots'
      path: '/api/screenshots'
      fullPath: '/api/screenshots'
      preLoaderRoute: typeof ApiScreenshotsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/users': {
      id: '/api/users'
      path: '/api/users'
      fullPath: '/api/users'
      preLoaderRoute: typeof ApiUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/channels/$id': {
      id: '/api/channels/$id'
      path: '/api/channels/$id'
      fullPath: '/api/channels/$id'
      preLoaderRoute: typeof ApiChannelsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/countries/$id': {
      id: '/api/countries/$id'
      path: '/$id'
      fullPath: '/api/countries/$id'
      preLoaderRoute: typeof ApiCountriesIdRouteImport
      parentRoute: typeof ApiCountriesRoute
    }
    '/api/credentials/$id': {
      id: '/api/credentials/$id'
      path: '/$id'
      fullPath: '/api/credentials/$id'
      preLoaderRoute: typeof ApiCredentialsIdRouteImport
      parentRoute: typeof ApiCredentialsRoute
    }
    '/api/push/subscribe': {
      id: '/api/push/subscribe'
      path: '/api/push/subscribe'
      fullPath: '/api/push/subscribe'
      preLoaderRoute: typeof ApiPushSubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/push/subscriptions': {
      id: '/api/push/subscriptions'
      path: '/api/push/subscriptions'
      fullPath: '/api/push/subscriptions'
      preLoaderRoute: typeof ApiPushSubscriptionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/push/vapid-public-key': {
      id: '/api/push/vapid-public-key'
      path: '/api/push/vapid-public-key'
      fullPath: '/api/push/vapid-public-key'
      preLoaderRoute: typeof ApiPushVapidPublicKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/regions/$id': {
      id: '/api/regions/$id'
      path: '/api/regions/$id'
      fullPath: '/api/regions/$id'
      preLoaderRoute: typeof ApiRegionsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/reports/by-user': {
      id: '/api/reports/by-user'
      path: '/api/reports/by-user'
      fullPath: '/api/reports/by-user'
      preLoaderRoute: typeof ApiReportsByUserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/requests/$id': {
      id: '/api/requests/$id'
      path: '/$id'
      fullPath: '/api/requests/$id'
      preLoaderRoute: typeof ApiRequestsIdRouteImport
      parentRoute: typeof ApiRequestsRoute
    }
    '/api/screenshots/$key': {
      id: '/api/screenshots/$key'
      path: '/$key'
      fullPath: '/api/screenshots/$key'
      preLoaderRoute: typeof ApiScreenshotsKeyRouteImport
      parentRoute: typeof ApiScreenshotsRoute
    }
    '/api/users/invite': {
      id: '/api/users/invite'
      path: '/invite'
      fullPath: '/api/users/invite'
      preLoaderRoute: typeof ApiUsersInviteRouteImport
      parentRoute: typeof ApiUsersRoute
    }
    '/api/channels/$id/test': {
      id: '/api/channels/$id/test'
      path: '/test'
      fullPath: '/api/channels/$id/test'
      preLoaderRoute: typeof ApiChannelsIdTestRouteImport
      parentRoute: typeof ApiChannelsIdRoute
    }
    '/api/countries/$id/channels': {
      id: '/api/countries/$id/channels'
      path: '/channels'
      fullPath: '/api/countries/$id/channels'
      preLoaderRoute: typeof ApiCountriesIdChannelsRouteImport
      parentRoute: typeof ApiCountriesIdRoute
    }
    '/api/countries/$id/regions': {
      id: '/api/countries/$id/regions'
      path: '/regions'
      fullPath: '/api/countries/$id/regions'
      preLoaderRoute: typeof ApiCountriesIdRegionsRouteImport
      parentRoute: typeof ApiCountriesIdRoute
    }
    '/api/push/subscriptions/$id': {
      id: '/api/push/subscriptions/$id'
      path: '/$id'
      fullPath: '/api/push/subscriptions/$id'
      preLoaderRoute: typeof ApiPushSubscriptionsIdRouteImport
      parentRoute: typeof ApiPushSubscriptionsRoute
    }
    '/api/users/$id/access': {
      id: '/api/users/$id/access'
      path: '/$id/access'
      fullPath: '/api/users/$id/access'
      preLoaderRoute: typeof ApiUsersIdAccessRouteImport
      parentRoute: typeof ApiUsersRoute
    }
    '/api/users/$id/reset-password': {
      id: '/api/users/$id/reset-password'
      path: '/$id/reset-password'
      fullPath: '/api/users/$id/reset-password'
      preLoaderRoute: typeof ApiUsersIdResetPasswordRouteImport
      parentRoute: typeof ApiUsersRoute
    }
  }
}

interface ProtectedRouteChildren {
  ProtectedAdminRoute: typeof ProtectedAdminRoute
  ProtectedReportsRoute: typeof ProtectedReportsRoute
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedAdminRoute: ProtectedAdminRoute,
  ProtectedReportsRoute: ProtectedReportsRoute,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

interface ApiCountriesIdRouteChildren {
  ApiCountriesIdChannelsRoute: typeof ApiCountriesIdChannelsRoute
  ApiCountriesIdRegionsRoute: typeof ApiCountriesIdRegionsRoute
}

const ApiCountriesIdRouteChildren: ApiCountriesIdRouteChildren = {
  ApiCountriesIdChannelsRoute: ApiCountriesIdChannelsRoute,
  ApiCountriesIdRegionsRoute: ApiCountriesIdRegionsRoute,
}

const ApiCountriesIdRouteWithChildren = ApiCountriesIdRoute._addFileChildren(
  ApiCountriesIdRouteChildren,
)

interface ApiCountriesRouteChildren {
  ApiCountriesIdRoute: typeof ApiCountriesIdRouteWithChildren
}

const ApiCountriesRouteChildren: ApiCountriesRouteChildren = {
  ApiCountriesIdRoute: ApiCountriesIdRouteWithChildren,
}

const ApiCountriesRouteWithChildren = ApiCountriesRoute._addFileChildren(
  ApiCountriesRouteChildren,
)

interface ApiCredentialsRouteChildren {
  ApiCredentialsIdRoute: typeof ApiCredentialsIdRoute
}

const ApiCredentialsRouteChildren: ApiCredentialsRouteChildren = {
  ApiCredentialsIdRoute: ApiCredentialsIdRoute,
}

const ApiCredentialsRouteWithChildren = ApiCredentialsRoute._addFileChildren(
  ApiCredentialsRouteChildren,
)

interface ApiRequestsRouteChildren {
  ApiRequestsIdRoute: typeof ApiRequestsIdRoute
}

const ApiRequestsRouteChildren: ApiRequestsRouteChildren = {
  ApiRequestsIdRoute: ApiRequestsIdRoute,
}

const ApiRequestsRouteWithChildren = ApiRequestsRoute._addFileChildren(
  ApiRequestsRouteChildren,
)

interface ApiScreenshotsRouteChildren {
  ApiScreenshotsKeyRoute: typeof ApiScreenshotsKeyRoute
}

const ApiScreenshotsRouteChildren: ApiScreenshotsRouteChildren = {
  ApiScreenshotsKeyRoute: ApiScreenshotsKeyRoute,
}

const ApiScreenshotsRouteWithChildren = ApiScreenshotsRoute._addFileChildren(
  ApiScreenshotsRouteChildren,
)

interface ApiUsersRouteChildren {
  ApiUsersInviteRoute: typeof ApiUsersInviteRoute
  ApiUsersIdAccessRoute: typeof ApiUsersIdAccessRoute
  ApiUsersIdResetPasswordRoute: typeof ApiUsersIdResetPasswordRoute
}

const ApiUsersRouteChildren: ApiUsersRouteChildren = {
  ApiUsersInviteRoute: ApiUsersInviteRoute,
  ApiUsersIdAccessRoute: ApiUsersIdAccessRoute,
  ApiUsersIdResetPasswordRoute: ApiUsersIdResetPasswordRoute,
}

const ApiUsersRouteWithChildren = ApiUsersRoute._addFileChildren(
  ApiUsersRouteChildren,
)

interface ApiChannelsIdRouteChildren {
  ApiChannelsIdTestRoute: typeof ApiChannelsIdTestRoute
}

const ApiChannelsIdRouteChildren: ApiChannelsIdRouteChildren = {
  ApiChannelsIdTestRoute: ApiChannelsIdTestRoute,
}

const ApiChannelsIdRouteWithChildren = ApiChannelsIdRoute._addFileChildren(
  ApiChannelsIdRouteChildren,
)

interface ApiPushSubscriptionsRouteChildren {
  ApiPushSubscriptionsIdRoute: typeof ApiPushSubscriptionsIdRoute
}

const ApiPushSubscriptionsRouteChildren: ApiPushSubscriptionsRouteChildren = {
  ApiPushSubscriptionsIdRoute: ApiPushSubscriptionsIdRoute,
}

const ApiPushSubscriptionsRouteWithChildren =
  ApiPushSubscriptionsRoute._addFileChildren(ApiPushSubscriptionsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProtectedRoute: ProtectedRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  HelpRoute: HelpRoute,
  LoginRoute: LoginRoute,
  PrivacyRoute: PrivacyRoute,
  RequestsRoute: RequestsRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  TermsRoute: TermsRoute,
  ApiCountriesRoute: ApiCountriesRouteWithChildren,
  ApiCredentialsRoute: ApiCredentialsRouteWithChildren,
  ApiFeedRoute: ApiFeedRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiMeRoute: ApiMeRoute,
  ApiRequestsRoute: ApiRequestsRouteWithChildren,
  ApiScreenshotsRoute: ApiScreenshotsRouteWithChildren,
  ApiUsersRoute: ApiUsersRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiChannelsIdRoute: ApiChannelsIdRouteWithChildren,
  ApiPushSubscribeRoute: ApiPushSubscribeRoute,
  ApiPushSubscriptionsRoute: ApiPushSubscriptionsRouteWithChildren,
  ApiPushVapidPublicKeyRoute: ApiPushVapidPublicKeyRoute,
  ApiRegionsIdRoute: ApiRegionsIdRoute,
  ApiReportsByUserRoute: ApiReportsByUserRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
