/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProtectedRouteImport } from './routes/_protected'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ProtectedIndexRouteImport } from './routes/_protected/index'
import { Route as ProtectedAdminRouteImport } from './routes/_protected/admin'
import { Route as ProtectedReportsRouteImport } from './routes/_protected/reports'
import { Route as ApiCountriesRouteImport } from './routes/api/countries'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as ApiRequestsRouteImport } from './routes/api/requests'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiChannelsIdRouteImport } from './routes/api/channels/$id'
import { Route as ApiCountriesIdRouteImport } from './routes/api/countries/$id'
import { Route as ApiReportsByUserRouteImport } from './routes/api/reports/by-user'
import { Route as ApiRequestsIdRouteImport } from './routes/api/requests/$id'
import { Route as ApiChannelsIdTestRouteImport } from './routes/api/channels/$id/test'
import { Route as ApiCountriesIdChannelsRouteImport } from './routes/api/countries/$id/channels'

const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedIndexRoute = ProtectedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedAdminRoute = ProtectedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedReportsRoute = ProtectedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => ProtectedRoute,
} as any)
const ApiCountriesRoute = ApiCountriesRouteImport.update({
  id: '/api/countries',
  path: '/api/countries',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRequestsRoute = ApiRequestsRouteImport.update({
  id: '/api/requests',
  path: '/api/requests',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChannelsIdRoute = ApiChannelsIdRouteImport.update({
  id: '/api/channels/$id',
  path: '/api/channels/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCountriesIdRoute = ApiCountriesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiCountriesRoute,
} as any)
const ApiReportsByUserRoute = ApiReportsByUserRouteImport.update({
  id: '/api/reports/by-user',
  path: '/api/reports/by-user',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRequestsIdRoute = ApiRequestsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiRequestsRoute,
} as any)
const ApiChannelsIdTestRoute = ApiChannelsIdTestRouteImport.update({
  id: '/test',
  path: '/test',
  getParentRoute: () => ApiChannelsIdRoute,
} as any)
const ApiCountriesIdChannelsRoute = ApiCountriesIdChannelsRouteImport.update({
  id: '/channels',
  path: '/channels',
  getParentRoute: () => ApiCountriesIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof ProtectedIndexRoute
  '/login': typeof LoginRoute
  '/admin': typeof ProtectedAdminRoute
  '/reports': typeof ProtectedReportsRoute
  '/api/countries': typeof ApiCountriesRouteWithChildren
  '/api/health': typeof ApiHealthRoute
  '/api/requests': typeof ApiRequestsRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/channels/$id': typeof ApiChannelsIdRouteWithChildren
  '/api/countries/$id': typeof ApiCountriesIdRouteWithChildren
  '/api/reports/by-user': typeof ApiReportsByUserRoute
  '/api/requests/$id': typeof ApiRequestsIdRoute
  '/api/channels/$id/test': typeof ApiChannelsIdTestRoute
  '/api/countries/$id/channels': typeof ApiCountriesIdChannelsRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/admin': typeof ProtectedAdminRoute
  '/reports': typeof ProtectedReportsRoute
  '/api/countries': typeof ApiCountriesRouteWithChildren
  '/api/health': typeof ApiHealthRoute
  '/api/requests': typeof ApiRequestsRouteWithChildren
  '/': typeof ProtectedIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/channels/$id': typeof ApiChannelsIdRouteWithChildren
  '/api/countries/$id': typeof ApiCountriesIdRouteWithChildren
  '/api/reports/by-user': typeof ApiReportsByUserRoute
  '/api/requests/$id': typeof ApiRequestsIdRoute
  '/api/channels/$id/test': typeof ApiChannelsIdTestRoute
  '/api/countries/$id/channels': typeof ApiCountriesIdChannelsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_protected': typeof ProtectedRouteWithChildren
  '/login': typeof LoginRoute
  '/_protected/admin': typeof ProtectedAdminRoute
  '/_protected/reports': typeof ProtectedReportsRoute
  '/api/countries': typeof ApiCountriesRouteWithChildren
  '/api/health': typeof ApiHealthRoute
  '/api/requests': typeof ApiRequestsRouteWithChildren
  '/_protected/': typeof ProtectedIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/channels/$id': typeof ApiChannelsIdRouteWithChildren
  '/api/countries/$id': typeof ApiCountriesIdRouteWithChildren
  '/api/reports/by-user': typeof ApiReportsByUserRoute
  '/api/requests/$id': typeof ApiRequestsIdRoute
  '/api/channels/$id/test': typeof ApiChannelsIdTestRoute
  '/api/countries/$id/channels': typeof ApiCountriesIdChannelsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/admin'
    | '/reports'
    | '/api/countries'
    | '/api/health'
    | '/api/requests'
    | '/api/auth/$'
    | '/api/channels/$id'
    | '/api/countries/$id'
    | '/api/reports/by-user'
    | '/api/requests/$id'
    | '/api/channels/$id/test'
    | '/api/countries/$id/channels'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/admin'
    | '/reports'
    | '/api/countries'
    | '/api/health'
    | '/api/requests'
    | '/'
    | '/api/auth/$'
    | '/api/channels/$id'
    | '/api/countries/$id'
    | '/api/reports/by-user'
    | '/api/requests/$id'
    | '/api/channels/$id/test'
    | '/api/countries/$id/channels'
  id:
    | '__root__'
    | '/_protected'
    | '/login'
    | '/_protected/admin'
    | '/_protected/reports'
    | '/api/countries'
    | '/api/health'
    | '/api/requests'
    | '/_protected/'
    | '/api/auth/$'
    | '/api/channels/$id'
    | '/api/countries/$id'
    | '/api/reports/by-user'
    | '/api/requests/$id'
    | '/api/channels/$id/test'
    | '/api/countries/$id/channels'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ProtectedRoute: typeof ProtectedRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiCountriesRoute: typeof ApiCountriesRouteWithChildren
  ApiHealthRoute: typeof ApiHealthRoute
  ApiRequestsRoute: typeof ApiRequestsRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiChannelsIdRoute: typeof ApiChannelsIdRouteWithChildren
  ApiReportsByUserRoute: typeof ApiReportsByUserRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/': {
      id: '/_protected/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ProtectedIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/admin': {
      id: '/_protected/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof ProtectedAdminRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/reports': {
      id: '/_protected/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ProtectedReportsRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/api/countries': {
      id: '/api/countries'
      path: '/api/countries'
      fullPath: '/api/countries'
      preLoaderRoute: typeof ApiCountriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/requests': {
      id: '/api/requests'
      path: '/api/requests'
      fullPath: '/api/requests'
      preLoaderRoute: typeof ApiRequestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/channels/$id': {
      id: '/api/channels/$id'
      path: '/api/channels/$id'
      fullPath: '/api/channels/$id'
      preLoaderRoute: typeof ApiChannelsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/countries/$id': {
      id: '/api/countries/$id'
      path: '/$id'
      fullPath: '/api/countries/$id'
      preLoaderRoute: typeof ApiCountriesIdRouteImport
      parentRoute: typeof ApiCountriesRoute
    }
    '/api/reports/by-user': {
      id: '/api/reports/by-user'
      path: '/api/reports/by-user'
      fullPath: '/api/reports/by-user'
      preLoaderRoute: typeof ApiReportsByUserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/requests/$id': {
      id: '/api/requests/$id'
      path: '/$id'
      fullPath: '/api/requests/$id'
      preLoaderRoute: typeof ApiRequestsIdRouteImport
      parentRoute: typeof ApiRequestsRoute
    }
    '/api/channels/$id/test': {
      id: '/api/channels/$id/test'
      path: '/test'
      fullPath: '/api/channels/$id/test'
      preLoaderRoute: typeof ApiChannelsIdTestRouteImport
      parentRoute: typeof ApiChannelsIdRoute
    }
    '/api/countries/$id/channels': {
      id: '/api/countries/$id/channels'
      path: '/channels'
      fullPath: '/api/countries/$id/channels'
      preLoaderRoute: typeof ApiCountriesIdChannelsRouteImport
      parentRoute: typeof ApiCountriesIdRoute
    }
  }
}

interface ProtectedRouteChildren {
  ProtectedAdminRoute: typeof ProtectedAdminRoute
  ProtectedReportsRoute: typeof ProtectedReportsRoute
  ProtectedIndexRoute: typeof ProtectedIndexRoute
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedAdminRoute: ProtectedAdminRoute,
  ProtectedReportsRoute: ProtectedReportsRoute,
  ProtectedIndexRoute: ProtectedIndexRoute,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

interface ApiCountriesIdRouteChildren {
  ApiCountriesIdChannelsRoute: typeof ApiCountriesIdChannelsRoute
}

const ApiCountriesIdRouteChildren: ApiCountriesIdRouteChildren = {
  ApiCountriesIdChannelsRoute: ApiCountriesIdChannelsRoute,
}

const ApiCountriesIdRouteWithChildren = ApiCountriesIdRoute._addFileChildren(
  ApiCountriesIdRouteChildren,
)

interface ApiCountriesRouteChildren {
  ApiCountriesIdRoute: typeof ApiCountriesIdRouteWithChildren
}

const ApiCountriesRouteChildren: ApiCountriesRouteChildren = {
  ApiCountriesIdRoute: ApiCountriesIdRouteWithChildren,
}

const ApiCountriesRouteWithChildren = ApiCountriesRoute._addFileChildren(
  ApiCountriesRouteChildren,
)

interface ApiRequestsRouteChildren {
  ApiRequestsIdRoute: typeof ApiRequestsIdRoute
}

const ApiRequestsRouteChildren: ApiRequestsRouteChildren = {
  ApiRequestsIdRoute: ApiRequestsIdRoute,
}

const ApiRequestsRouteWithChildren = ApiRequestsRoute._addFileChildren(
  ApiRequestsRouteChildren,
)

interface ApiChannelsIdRouteChildren {
  ApiChannelsIdTestRoute: typeof ApiChannelsIdTestRoute
}

const ApiChannelsIdRouteChildren: ApiChannelsIdRouteChildren = {
  ApiChannelsIdTestRoute: ApiChannelsIdTestRoute,
}

const ApiChannelsIdRouteWithChildren = ApiChannelsIdRoute._addFileChildren(
  ApiChannelsIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  ProtectedRoute: ProtectedRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiCountriesRoute: ApiCountriesRouteWithChildren,
  ApiHealthRoute: ApiHealthRoute,
  ApiRequestsRoute: ApiRequestsRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiChannelsIdRoute: ApiChannelsIdRouteWithChildren,
  ApiReportsByUserRoute: ApiReportsByUserRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
